# Generated by Django 4.2.15 on 2024-09-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
