# Generated by Django 4.2.15 on 2024-09-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='level',
            new_name='BodyPart',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='workout',
            name='Level',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='Type',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserWorkout',
        ),
        migrations.AddField(
            model_name='workout',
            name='Equipment',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
