# Generated by Django 4.2.15 on 2024-09-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_userprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
