# Generated by Django 4.2.15 on 2024-09-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_userprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'User Progress', 'verbose_name_plural': 'User Progresses'},
        ),
    ]
