# Generated by Django 4.2.15 on 2024-09-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0007_alter_userprogress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'List of User Progress', 'verbose_name_plural': 'User Progress'},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'List of Workouts', 'verbose_name_plural': 'Workouts'},
        ),
    ]
