# Generated by Django 4.2.15 on 2024-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0011_remove_userprofile_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Diabetes',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Fitness_Goal',
            field=models.CharField(default='Weight_Loss', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Fitness_Type',
            field=models.CharField(default='Cardio_Fitness', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Hypertension',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Level',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
