# Generated by Django 4.2.15 on 2024-10-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0014_userprofile_diabetes_userprofile_fitness_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Level',
        ),
    ]
