# Generated by Django 4.2.15 on 2024-10-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0015_remove_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Level',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
